media: assets/images
content:
  - name: products
    label: Produkter
    path: products
    type: collection
    filename: {fields.productName}
    fields:
      - name: layout
        label: Layout
        default: product
        type: string
      - name: productName
        label: Produktnavn
        type: string
        required: true
      - name: producer
        label: Produsent
        type: string
        required: true
    view:
      fields: [productName, producer]