media: assets/images
content:
  - name: products
    label: Produkter
    path: products
    type: collection
    view:
      fields: [ productName, producer ]
    fields:
      - { name: layout, label: Layout, default: product, type: string }
      - { name: productName, label: Produktnavn, type: string, required: true }
      - { name: producer, label: Produsent, type: string, required: true }
    filename: fields.productName